matrix:
  include:
    - language: php
      php:
        - 7.0.23
      directories:
        - $HOME/.composer/cache/files
      script:
        - composer install --no-interaction --no-autoloader --prefer-dist
        - vendor/bin/phpcs .  --runtime-set ignore_warnings_on_exit 1
    - language: node_js
      node_js:
        - 8
      cache:
        directories:
          - $HOME/js/node_modules
        script:
          - npm run build